### ISSUE TITLE
New jinjify system fails on import of 'click' module.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/ots-doctools#5]
I tried to build one of our pre-jinjification documents -- the name of the document is slightly disguised below, but the client name is real, as we've been public about the fact that we're working with that client -- and got an error about how Python couldn't find the `click` library.  What's odd is that `click` claims to be installed on the system.  Details in the transcript below.

I can solve this, obviously, and will document here how I do so.  But it would be nice if we gave a better error on import failures for any non-core libraries.

Also: when we were first discussing this system, we decided (IIRC) that we'd run jinjify unconditionally, even if there are no jinja templates in the document.  I still think that might be the right decision, and it's obviously what we're doing here (this document has no Jinja templates since it predates the Grand Jinjification), but we should note somewhere that we've now made the official OTS markup language be LaTeX-plus-Jinja.  E.g., if we were ever writing a LaTeX doc that included a discussion *about* Jinja templates, then we'd still have to escape all the Jinja template examples given in that doc even if the doc itself didn't use Jinja templating.  I'm not saying that situation is likely to come up; I'm just saying that we should decide unambiguously what our markup language is so that we can avoid unpleasant surprises down the road.  (Encountering this bug made me think of this, even though this bug is not an instance of this.)

Here's the transcript of the `click` import problem:

```
$ cd ${OTSDIR}/clients/mozilla/archetypes/deliverables/
$ make mozilla-in-progress-report.pdf 
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/bin/python3
Also creating executable in /home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Collecting python-frontmatter
  Using cached https://files.pythonhosted.org/packages/7f/06/a4141a23bff3fb27e634a38a500da71aa155aca28e8b9d635ea591651375/python_frontmatter-0.4.5-py3-none-any.whl
Collecting jinja2
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting six (from python-frontmatter)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting PyYAML (from python-frontmatter)
Collecting MarkupSafe>=0.23 (from jinja2)
  Using cached https://files.pythonhosted.org/packages/98/7b/ff284bd8c80654e471b769062a9b43cc5d03e7a615048d96f4619df8d420/MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: six, PyYAML, python-frontmatter, MarkupSafe, jinja2
Successfully installed MarkupSafe-1.1.1 PyYAML-5.1.1 jinja2-2.10.1 python-frontmatter-0.4.5 six-1.12.0
Traceback (most recent call last):
  File "/home/kfogel/private/work/ots/r/ots-doctools/jinja/jinjify.py", line 18, in <module>
    import click
ModuleNotFoundError: No module named 'click'
make[1]: *** [/home/kfogel/private/work/ots/r/ots-doctools/Makefile:78: mozilla-in-progress-report.pdf] Error 1
make: *** [Makefile:23: mozilla-in-progress-report.pdf] Error 2
$ sudo apt-get install python-click
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-click is already the newest version (7.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ sudo apt-get install python3-click
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-click is already the newest version (7.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ make mozilla-in-progress-report.pdf 
Traceback (most recent call last):
  File "/home/kfogel/private/work/ots/r/ots-doctools/jinja/jinjify.py", line 18, in <module>
    import click
ModuleNotFoundError: No module named 'click'
make[1]: *** [/home/kfogel/private/work/ots/r/ots-doctools/Makefile:78: mozilla-in-progress-report.pdf] Error 1
make: *** [Makefile:23: mozilla-in-progress-report.pdf] Error 2
$ 
```

**Comment by kfogel** [comment]
Okay, commit e92333937a adds `click` to the list of dependencies to install in the virtual env.  Now I get a different failure -- which is a sign of progress, at least!  (And maybe a sign that this bug should be closed and a new one opened, but I'm not sure yet.)

```
$ rm -rf venv
$ make mozilla-in-progress-report.pdf 
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/bin/python3
Also creating executable in /home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Collecting python-frontmatter
  Using cached https://files.pythonhosted.org/packages/7f/06/a4141a23bff3fb27e634a38a500da71aa155aca28e8b9d635ea591651375/python_frontmatter-0.4.5-py3-none-any.whl
Collecting jinja2
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting click
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
     |████████████████████████████████| 81kB 301kB/s 
Collecting six (from python-frontmatter)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting PyYAML (from python-frontmatter)
Collecting MarkupSafe>=0.23 (from jinja2)
  Using cached https://files.pythonhosted.org/packages/98/7b/ff284bd8c80654e471b769062a9b43cc5d03e7a615048d96f4619df8d420/MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: six, PyYAML, python-frontmatter, MarkupSafe, jinja2, click
Successfully installed MarkupSafe-1.1.1 PyYAML-5.1.1 click-7.0 jinja2-2.10.1 python-frontmatter-0.4.5 six-1.12.0
Traceback (most recent call last):
  File "/home/kfogel/private/work/ots/r/ots-doctools/jinja/jinjify.py", line 83, in <module>
    jinjify()
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kfogel/private/work/ots/r/ots-doctools/jinja/jinjify.py", line 72, in jinjify
    template = latex_jinja_env.get_template('jinjify_me.ltx')
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 405, in load
    return loader.load(environment, name, globals)
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 54, in template
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/kfogel/private/work/ots/clients/mozilla/archetypes/deliverables/venv/lib/python3.7/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'setup'.
make[1]: *** [/home/kfogel/private/work/ots/r/ots-doctools/Makefile:78: mozilla-in-progress-report.pdf] Error 1
make: *** [Makefile:23: mozilla-in-progress-report.pdf] Error 2
$ 
```
